### ISSUE TITLE
How to use with an existing puppeteer project ?

### ISSUE THREAD

**Issue by KaKi87** [Eltik/Puppeteer-Bypass#4]
Hi,

I have an existing puppeteer project on which I've been using [`puppeteer-extra-plugin-stealth`](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth), like the following :

```js
import puppeteer from 'puppeteer-extra';
import puppeteerStealth from 'puppeteer-extra-plugin-stealth';
puppeteer.use(puppeteerStealth());
const browser = await puppeteer.launch({ headless: false });
// etc...
```

Which bypassed Cloudflare for a while, but failed at it lately.

So, I'd like to try your project instead, but I don't understand how to import it ?

Thanks

**Comment by Eltik** [comment]
Hey sorry for the late reply. You can clone the repository or just copy the `API.ts` file into your project. Then, use `import * as Puppeteer-Bypass from "./API.ts"`.

**Comment by KaKi87** [comment]
Would it be possible to import it as JS instead of TS ?
Also, how to use the `Puppeteer-Bypass` variable then ?

**Comment by Eltik** [comment]
Well in that case, you'd import the `API.js` file from the `./built` folder. And as shown in the documentation, simply `const bypass = new PuppeteerBypass()` (assuming your import is `import * as PuppeteerBypass from "./API.js"`).

**Comment by KaKi87** [comment]
Okay but then what, do I do `puppeteer.use(bypass)` or something ?
Thanks

**Comment by Eltik** [comment]
I see what you want, but that isn't how this project works. It can't be used as a puppeteer extension. I suggest reading the documentation [here](https://github.com/Eltik/Puppeteer-Bypass#using-as-a-library).

**Comment by KaKi87** [comment]
> It can't be used as a puppeteer extension.

Well, that answers my question, yes I've seen the README, but that's indeed not what I need 😅

Thanks anyway.

**Comment by rainb3rry** [comment]
> > It can't be used as a puppeteer extension.
> 
> Well, that answers my question, yes I've seen the README, but that's indeed not what I need 😅
> 
> Thanks anyway.

Hey @KaKi87 I have exactly the same problems lately, have you found any solution about that?

**Comment by KaKi87** [comment]
I did !

Here's the config that works :

```js
import puppeteer from 'puppeteer-extra';
import createPuppeteerStealth from 'puppeteer-extra-plugin-stealth';

const puppeteerStealth = createPuppeteerStealth();
puppeteerStealth.enabledEvasions.delete('user-agent-override'); // <-- Only for Linux
puppeteer.use(puppeteerStealth);

const browser = await puppeteer.launch({
    headless: false,
    targetFilter: target => target.type() !== 'other'
});
```

Source discussion : berstend/puppeteer-extra#817

++
